wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.16.2
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706377798.965482
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.9.5
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
